// eslint-disable-next-line import/prefer-default-export
export const types = {
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DONE_TODO: 'DONE_TODO',

  UPDATE_EDITED_TODO: 'UPDATE_EDITED_TODO',
  EDIT_TODO: 'EDIT_TODO',
  FILL_TODO: 'FILL_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  EDIT_CANCEL: 'EDIT_CANCEL',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
};
